name: IFCC Compiler Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jdk default-jre g++ make python3 antlr4 libantlr4-runtime-dev

    - name: Configure ANTLR paths for Ubuntu APT
      run: |
        echo "ANTLRJAR=/usr/share/java/antlr4.jar" > compiler/config.mk
        echo "ANTLRINC=/usr/include/antlr4-runtime" >> compiler/config.mk
        echo "ANTLRLIB=-lantlr4-runtime" >> compiler/config.mk

    - name: Build Compiler
      working-directory: ./compiler
      run: |
        make clean
        make -j4

    - name: Run Test Suite
      run: python3 ifcc-test.py testfiles/*.c
