name: IFCC Compiler Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jdk default-jre g++ make python3
        
        # Le runtime C++ pour Ubuntu 22.04 est ANTLR 4.9.3
        sudo apt-get install -y libantlr4-runtime-dev
        
        # On télécharge directement le jar "complete" pour éviter les bugs de classpath du package ubuntu
        wget https://www.antlr.org/download/antlr-4.9.3-complete.jar -O /tmp/antlr4.jar

    - name: Configure ANTLR paths for Ubuntu APT
      run: |
        echo "ANTLRJAR=/tmp/antlr4.jar" > compiler/config.mk
        echo "ANTLRINC=/usr/include/antlr4-runtime" >> compiler/config.mk
        echo "ANTLRLIB=-lantlr4-runtime" >> compiler/config.mk

    - name: Build Compiler
      working-directory: ./compiler
      run: |
        make clean
        make -j4

    - name: Run Test Suite
      run: python3 ifcc-test.py testfiles/*.c
